server:
    context-path: /springboot-hsqldb
    port: 9093
    application:
        name: authorization-service
spring:
    datasource:
        driver-class-name: org.hsqldb.jdbcDriver
        password: tony
        url: jdbc:hsqldb:file:D:\test\amdocs-credentials
        username: tony
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format: true
                format_sql: true
        show-sql: true

    kafka      :
        bootstrap-servers: 127.0.0.1:9092 #here you can define the cluster
        producer:
            key-serializer  : org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            acks            : 1
            retries         : 0
            batch-size      : 16384
            buffer-memory   : 33554432
        consumer:
            group-id: default_consumer_group
            enable-auto-commit: true
            auto-commit-interval: 1000
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    spring:
        cloud:
            loadbalancer:
                ribbon:
                    enable: true