server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: assignment-authorization
          uri: http://localhost:9092
          predicates:
            - Path=/assignment-authorization/**
          filters:
            - StripPrefix=1
        - id: assignment-profile
          uri: http://localhost:9091
          predicates:
            - Path=/assignment-profile/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:9091"
              - "http://localhost:9092"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600